
package com.slyadz.hrlist.service.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeWS", targetNamespace = "http://ws.service.hrlist.slyadz.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeWS {


    /**
     * 
     * @param employeeId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://ws.service.hrlist.slyadz.com/", className = "com.slyadz.hrlist.service.ws.DeleteEmployee")
    @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://ws.service.hrlist.slyadz.com/", className = "com.slyadz.hrlist.service.ws.DeleteEmployeeResponse")
    @Action(input = "http://ws.service.hrlist.slyadz.com/EmployeeWS/deleteEmployeeRequest", output = "http://ws.service.hrlist.slyadz.com/EmployeeWS/deleteEmployeeResponse")
    public boolean deleteEmployee(
        @WebParam(name = "employeeId", targetNamespace = "")
        long employeeId);

    /**
     * 
     * @param employee
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createEmployee", targetNamespace = "http://ws.service.hrlist.slyadz.com/", className = "com.slyadz.hrlist.service.ws.CreateEmployee")
    @ResponseWrapper(localName = "createEmployeeResponse", targetNamespace = "http://ws.service.hrlist.slyadz.com/", className = "com.slyadz.hrlist.service.ws.CreateEmployeeResponse")
    @Action(input = "http://ws.service.hrlist.slyadz.com/EmployeeWS/createEmployeeRequest", output = "http://ws.service.hrlist.slyadz.com/EmployeeWS/createEmployeeResponse")
    public boolean createEmployee(
        @WebParam(name = "employee", targetNamespace = "")
        Employee employee);

    /**
     * 
     * @param employee
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://ws.service.hrlist.slyadz.com/", className = "com.slyadz.hrlist.service.ws.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://ws.service.hrlist.slyadz.com/", className = "com.slyadz.hrlist.service.ws.UpdateEmployeeResponse")
    @Action(input = "http://ws.service.hrlist.slyadz.com/EmployeeWS/updateEmployeeRequest", output = "http://ws.service.hrlist.slyadz.com/EmployeeWS/updateEmployeeResponse")
    public boolean updateEmployee(
        @WebParam(name = "employee", targetNamespace = "")
        Employee employee);

    /**
     * 
     * @return
     *     returns java.util.List<com.slyadz.hrlist.service.ws.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllEmployees", targetNamespace = "http://ws.service.hrlist.slyadz.com/", className = "com.slyadz.hrlist.service.ws.GetAllEmployees")
    @ResponseWrapper(localName = "getAllEmployeesResponse", targetNamespace = "http://ws.service.hrlist.slyadz.com/", className = "com.slyadz.hrlist.service.ws.GetAllEmployeesResponse")
    @Action(input = "http://ws.service.hrlist.slyadz.com/EmployeeWS/getAllEmployeesRequest", output = "http://ws.service.hrlist.slyadz.com/EmployeeWS/getAllEmployeesResponse")
    public List<Employee> getAllEmployees();

    /**
     * 
     * @param departmentId
     * @return
     *     returns java.util.List<com.slyadz.hrlist.service.ws.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeesByDepartment", targetNamespace = "http://ws.service.hrlist.slyadz.com/", className = "com.slyadz.hrlist.service.ws.GetEmployeesByDepartment")
    @ResponseWrapper(localName = "getEmployeesByDepartmentResponse", targetNamespace = "http://ws.service.hrlist.slyadz.com/", className = "com.slyadz.hrlist.service.ws.GetEmployeesByDepartmentResponse")
    @Action(input = "http://ws.service.hrlist.slyadz.com/EmployeeWS/getEmployeesByDepartmentRequest", output = "http://ws.service.hrlist.slyadz.com/EmployeeWS/getEmployeesByDepartmentResponse")
    public List<Employee> getEmployeesByDepartment(
        @WebParam(name = "departmentId", targetNamespace = "")
        long departmentId);

}
